### ISSUE TITLE
Problems with promoting blog to website

### ISSUE THREAD

**Issue by CNG** [danwolfgang/mt-plugin-website-blog-organizer#1] opened 2014-05-09 05:18 UTC
Hi Dan, 

I tried this on my personal site as well as a test install. This is the basic scenario of an MT4 install with one blog representing the "main blog" or homepage, and after upgrading to MT5, all the blogs are under a new website. I then want to essentially replace that website with the main blog. So I promote the main blog, intending to later move the other blogs under that newly promoted website and delete the MT-created website.
1. Fresh MT6.0.3 installation.
2. Create website "Website 1" with URL `http://example.com/` and path `/var/www/`
3. Under Website 1, create blogs:
   1. "Blog 1 under Website 1" with URL `blog1/` (actually is `http://example.com/blog1`, but the first part is set by the website) and path `blog1`
   2. "Blog 2 under Website 1" with URL `blog2/` and path `blog2`
   3. "Homepage Blog under Website 1" with blank URL and no path after the prefilled part, intending to use as the root
4. Install Website and Blog Organizer plugin
5. Using plugin, promote "Homepage Blog under Website 1" to a website
6. Navigate to settings page for that website, and observe an erroneous message:
   
   > This website was created during the upgrade from a previous version of Movable Type. 'Site Root' and 'Site URL' are left blank to retain 'Publishing Paths' compatibility for blogs that were created in a previous version. You can post and publish on existing blogs, but you cannot publish this website itself because of the blank 'Site Root' and 'Site URL'.
   
   I understand why this message is here. I assume it's coming from MT and not this plugin, but just wanted to be clear.
7. **The main problem is I can't seem to set the Blog URL.** It defaults to `/::/`, and once I try to edit it, I cannot save the page, and just get a "You must set a valid URL." message. I can't save it as what it is now, nor can I set it to my desired URL `http://example.com/`.

I have screenshots if they help, but perhaps you can enlighten me on something I might have done wrong? Thank you Dan!

**Comment by danwolfgang** [comment] 2014-05-09 13:26
I think the `is_valid_url` JS in MT6+ is the trouble? I can recreate the problem you describe in 6.0 and 6.0.1 (haven't tried 6.0.2 or 6.0.3), but not in MT5.

I don't know how the plugin could be causing this, but to be honest I haven't investigated how the `is_valid_url` is calculating the `website_url` variable when checking the Site URL. I don't know if it's related to the version of MT, but I never see the message you see in step 6.

**Comment by yuji** [comment] 2014-05-27 06:41
hmm... I was not able to reproduce what charlie pointed out.

**Comment by CNG** [comment] 2014-05-27 06:43
@yuji let’s try it together tomorrow before our meeting

**Comment by yuji** [comment] 2014-05-27 06:44
Okay!

**Comment by CNG** [comment] 2014-09-29 13:11
Hi Dan, could you take a look at the small changes at https://github.com/danwolfgang/mt-plugin-website-blog-organizer/pull/2 that should solve my above issues? We are looking at promoting this plugin for use in upgrades. Thanks you!

**Comment by danwolfgang** [comment] 2014-09-30 21:00
Sorry for the delay, Charlie; too many things to do and keep track of. I've merged the commit and bumped this to version 1.0.1.

**Closed as completed by danwolfgang** 2014-09-30 21:00 UTC

**Comment by CNG** [comment] 2014-10-01 03:41
I know, my plate is bigger than ever as well… thank you so much!
